# Copyright 2019 RStudio, Inc.
# All rights reserved.
#
# Use of this source code is governed by a BSD 2-Clause
# license that can be found in the LICENSE_BSD file.

language: python
services:
  - docker
python:
  - 3.6
script:
  # --no-binary buildbot is required because buildbot doesn't bundle its tests
  # to binary wheels, but ursabot's test suite depends on buildbot's so install
  # it from source
  - pip install --no-binary buildbot "pytest>=3.9" mock flake8 -e .

  # run linter
  - flake8 ursabot

  # run the worker tests (docker utilities for now)
  - pytest -v ursabot

  # check the ursabot buildbot configurations
  - buildbot checkconfig projects/ursabot/test.cfg
  - buildbot checkconfig projects/ursabot/prod.cfg

  # check the arrow buildbot configurations
  - buildbot checkconfig projects/arrow/test.cfg
  - buildbot checkconfig projects/arrow/prod.cfg

  # check the configurations icluding both projects
  - buildbot checkconfig projects/arrow/both_test.cfg
  - buildbot checkconfig projects/arrow/both_prod.cfg
