# Copyright 2019 RStudio, Inc.
# All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

language: python
services:
  - docker
python:
  - 3.6
script:
  # --no-binary buildbot is required because buildbot doesn't bundle its tests
  # to binary wheels, but ursabot's test suite depends on buildbot's so install
  # it from source
  - pip install --no-binary buildbot "pytest>=3.9" mock flake8 -e .

  # run linter
  - flake8 ursabot

  # run the worker tests (docker utilities for now)
  - pytest -v ursabot

  # check the buildbot configuration
  - buildbot checkconfig
