title = 'Ursabot Testing'
url = 'http://localhost:8100/'
webui_port = 8100
database_url = 'sqlite:///ursabot.sqlite'

[github]
  token = "invalid_token"

[projects]

  [projects.ursabot]
  enabled = true

  [projects.arrow]
  enabled = true

[reporters]
  [reporters.github_status]
    enabled = false
    debug = true

  [reporters.github_review]
    enabled = false
    debug = true

[[workers]]
# docker-on-mac is able to containers for multiple architectures
name = 'local1'
arch = 'amd64'
docker.host = 'unix://var/run/docker.sock'
docker.hostconfig = { network_mode = 'host', cpuset_cpus = '0,1' }

[[workers]]
name = 'local2'
arch = 'amd64'
is_benchmark = true
docker.host = 'unix://var/run/docker.sock'
docker.hostconfig = { network_mode = 'host', cpuset_cpus = '2,3' }
